language: r
cache: packages

r_github_packages:
    - rstudio/blogdown

before_script:
    - Rscript -e 'blogdown::install_hugo(version = "0.20.7")'

script:
    - Rscript -e 'blogdown::build_site()'


